name: Daily Commit Summary

on:
  schedule:
    - cron: '0 18:30 * * *'  # Runs every day at midnight IST
  workflow_dispatch:

jobs:
  generate-summary:
    runs-on: ubuntu-latest

    steps:
    - name: Set timezone to IST
      uses: szenius/set-timezone@v2.0
      with:
        timezoneLinux: 'Asia/Kolkata'
        timezoneMacos: 'Asia/Kolkata'
        timezoneWindows: 'India Standard Time'

    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install PyGithub

    - name: Generate summary
      run: |
        python generate_summary.py

    - name: Commit and push changes
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git add summary_*.md
        git commit -m 'Daily commit summary'
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}
